services:
  pgsql:
    image: postgres:15
    environment:
      POSTGRES_DB: ris_db
      POSTGRES_USER: risuserdb
      POSTGRES_PASSWORD: 'GHeaO9jCWHO9LulGk8vbetnB'
    ports:
      - "5432:5432"
    volumes:
      - ris-db:/var/lib/postgresql/data

  # Y dejamos Orthanc
  orthanc:
    image: jodogne/orthanc-plugins
    ports:
      - "8042:8042"
      - "4242:4242"
    volumes:
      - orthanc-db:/var/lib/orthanc/db
      - ./orthanc.json:/etc/orthanc/orthanc.json

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ris-redis:/data

volumes:
  ris-db:
  ris-redis:
  orthanc-db:
