worker_processes 1;
pid /home/raul/.local/nginx-run/run/nginx.pid;
error_log /home/raul/.local/nginx-run/logs/error.log;

events {
    worker_connections 1024;
}

http {
    client_body_temp_path /home/raul/.local/nginx-run/tmp/client_body;
    proxy_temp_path /home/raul/.local/nginx-run/tmp/proxy;
    fastcgi_temp_path /home/raul/.local/nginx-run/tmp/fastcgi;
    uwsgi_temp_path /home/raul/.local/nginx-run/tmp/uwsgi;
    scgi_temp_path /home/raul/.local/nginx-run/tmp/scgi;
    include /home/raul/.local/nginx-root/etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log /home/raul/.local/nginx-run/logs/access.log;
    sendfile on;
    keepalive_timeout 65;
    include /home/raul/Escritorio/RIS/backend/docker/lab-casa/nginx.conf;
}
